[package]
name = "v2_feed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
#html-escape = "0.2.11"
tinyjson = "2.3.0"
#urlencoding = "2.1.0"
